## Voronoi computation tests

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from controllers import *
from scipy import spatial

%matplotlib qt

# Generate points
points = np.random.rand(5,3)*2-1
print(points)

# Convex hull
# Each combination of 3 points is a triangle
max_area = 0
max_points = np.zeros((3,3))
for i in range(len(points)-2):
    for j in range(i+1,len(points)-1):
        for k in range(j+1,len(points)):
            # Compute aera of triangle
            v1 = points[j]-points[i]
            v2 = points[k]-points[i]
            area = np.linalg.norm(np.cross(v1,v2))/2
            if area>max_area:
                max_area = area
                max_points = np.array([points[i],points[j],points[k]])

print(f'Max area: {max_area} with points {max_points}')

# Volume of convex hull
hull = spatial.ConvexHull(points, incremental=True)
print(hull.volume)

# Visualize points
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(points[:,0], points[:,1], points[:,2],s=50)
plt.show()



[[ 0.55589961  0.23023411  0.40601683]
 [ 0.24414912 -0.05329024 -0.44422092]
 [ 0.79110755 -0.07827872 -0.81674167]
 [ 0.64688097  0.3359129   0.72393035]
 [-0.97851908  0.6236326   0.15550647]]
Max area: 1.3736922069706572 with points [[ 0.79110755 -0.07827872 -0.81674167]
 [ 0.64688097  0.3359129   0.72393035]
 [-0.97851908  0.6236326   0.15550647]]
0.09065045972454963


In [3]:
def find_combination(points, c):
    # Recursive loop
    if len(points) == c:
        yield points
    else:
        for i in range(len(points)):
            temp_points = points.copy()
            temp_points = np.delete(temp_points,i,axis=0)
            yield from find_combination(temp_points, c)


In [4]:
def combinations(n, k):
   result = []

   def backtrack(start, current_combination):
      if len(current_combination) == k:
         result.append(current_combination)
         return

      for i in range(start, n):
         backtrack(i+1, current_combination + [i])

   backtrack(0, [])
   return result

In [5]:
test = [1,2,3,4,5]
result=list(combinations(4,3))

print(result)

[[0, 1, 2], [0, 1, 3], [0, 2, 3], [1, 2, 3]]


In [28]:
points = np.array([[0,2],[-1,1], [2,2], [1,2.1]])
hull = spatial.ConvexHull(points, qhull_options='QG3')
print(hull.good)
# plt.figure()
# plt.plot(points[hull.vertices,0], points[hull.vertices,1], 'r--', lw=2)
# plt.scatter(points[:,0], points[:,1])
# plt.show()

[False False  True]


In [17]:
#pdcontrol = PdController(1, 0.1)

angle = np.pi/8
current_heading = np.array([np.cos(angle),np.sin(angle),0])
desired_heading = np.array([1,0,0])

control = pdcontrol.get_control_from_orientation(current_heading, desired_heading, 0.01)

print(control)

-0.3926990816987242


In [2]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import proj3d

%matplotlib qt
from helper_functions import scatter

MIN, MAX = -0.5,0.5
# Test for real size scatter dots
fig = plt.figure()
ax = fig.add_subplot(111)
data = np.array([[0,0,0]])
#ax.scatter(data[:,0], data[:,1], s=300)
#ax.add_patch(plt.Circle((0,0), 0.1, color='r', fill=True))
s = scatter(data[:,0], data[:,1], ax, 0.1)
d = ax.figure.dpi
e = ax.transData.transform
# x0, y0, _ = proj3d.proj_transform(0,0,0,ax.get_proj())
# x1, y1, _ = proj3d.proj_transform(0.2,0.2,0.2,ax.get_proj())
# t = np.mean(e((x1,y1)) - e((x0,y0)))
ax.grid(True)
ax.set_xlim([MIN, MAX])
ax.set_ylim([MIN, MAX])
ax.xaxis.set_ticks(np.arange(MIN, MAX, 0.1))
ax.yaxis.set_ticks(np.arange(MIN, MAX, 0.1))
ax.set_aspect(1)
s.set_data([[0.2,0.2]])
plt.show()